version: '3'
services:
  db:
    image: mysql:8.0.32
    container_name: seq_course
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: seq_example
    ports:
      - 3306:3306
    healthcheck:
      # Deve aguardar o banco ficar operacional
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5
    volumes:
      # adiciona scripts SQL para serem executados ao iniciar a DB
      - ./sql:/docker-entrypoint-initdb.d
